---
title: "Chapter 5.4"
output: html_notebook
---

## Load an existing model

```{r}
library(keras)
model <- load_model_hdf5("cats_and_dogs_small_2.h5")
model
```

## Preprocess a single image

```{r}

img_path <- "~/Data/kaggle/cats_and_dogs_small/test/cats/cat.1700.jpg"

img <- image_load(img_path, target_size = c(150, 150))
img_tensor <- image_to_array(img)
img_tensor <- array_reshape(img_tensor, c(1, 150, 150, 3))
img_tensor <- img_tensor / 255

dim(img_tensor)
plot(as.raster(img_tensor[1,,,]))
```

## A model with one input and multiple outputs (activations for each layer)

```{r}
# Pull out outputs of top eight layers
layer_outputs <- lapply(model$layers[1:8], function(layer) layer$output)
# Create a new model based on these outputs
activation_model <- keras_model(inputs = model$input, outputs = layer_outputs)
activations <- activation_model %>% predict(img_tensor)
```

## Plot activations

```{r}
plot_channel <- function(channel) {
  rotate <- function(x) t(apply(x, 2, rev))
  image(rotate(channel), axes = FALSE, asp = 1, col = terrain.colors(12))
}
first_layer_activations <- activations[[1]]
plot_channel(first_layer_activations[1,,,7])
```

## Visualizing all the activations

```{r}
image_size <- 58
images_per_row <- 16

for (i in 1:8) {
  
  layer_activation <- activations[[i]]
  layer_name <- model$layers[[i]]$name
  
  n_features <- dim(layer_activation)[[4]]
  n_rows <- n_features %/% images_per_row
  
  png(paste0("cat_activations_", i, "_", layer_name, ".png"), 
      width = image_size * images_per_row,
      height = image_size * n_rows)
  op <- par(mfrow = c(n_rows, images_per_row), mai = rep_len(0.02, 4))
  
  for (row in 0:(n_rows - 1)) {
    for (col in 0:(images_per_row - 1)) {
      channel_image <- layer_activation[1,,,(row*images_per_row) + col + 1]
      plot_channel(channel_image)
    }
  }
  
  par(op)
  dev.off()
}
```

## Visualizing convnet filters

```{r}
library(keras)

model <- application_vgg16(
  weights = "imagenet",
  include_top = FALSE
)

deprocess_image <- function(x) {
  dms <- dim(x)
  x <- x - mean(x)
  x <- x / (sd(x) + 1e-5)
  x <- x * 0.1
  x <- x + 0.5
  x <- pmax(0, pmin(x, 1))
  array(x, dim = dms)
}

generate_pattern <- function(layer_name, filter_index, size = 150) {
  
  layer_output <- model$get_layer(layer_name)$output
  loss <- k_mean(layer_output[,,,filter_index])
  
  grads <- k_gradients(loss, model$input)[[1]]
  
  # normalize gradients to ensure updates stay a consistent size
  grads <- grads / (k_sqrt(k_mean(k_square(grads))) + 1e-5)
  
  iterate <- k_function(list(model$input), list(loss, grads))
  
  input_img_data <- array(runif(size * size * 3), dim = c(1, size, size, 3)) * 20 + 128
  
  step <- 1
  for (i in 1:40) {
    c(loss_value, grads_value) %<-% iterate(list(input_img_data))
    input_img_data <- input_img_data + (grads_value * step)
  }
  img <- input_img_data[1,,,]
  deprocess_image(img)
}

```

## Visualizing a single filter

```{r}
library(grid)
grid.newpage()
grid.raster(generate_pattern("block3_conv1", 1))

```

## Visualizing all the filters

```{r}
library(grid)
library(gridExtra)
dir.create("vgg_filters")

for (layer_name in c("block1_conv1", "block2_conv1", "block3_conv1", "block4_conv1")) {
  size <- 140
  
  png(paste0("vgg_filters/", layer_name, ".png"), width = 8 * size, height = 8 * size)
  
  grobs <- list()
  
  for (i in 0:7) {
    for (j in 0:7) {
      pattern <- generate_pattern(layer_name, i + (j*8) + 1, size = size)
      grob <- rasterGrob(pattern, width = unit(0.9, "npc"), height = unit(0.9, "npc"))
      grobs[[length(grobs) + 1]] <- grob
    }
  }
  
  grid.arrange(grobs = grobs, ncol = 8)
  dev.off()
}
```